# -*- coding: utf-8 -*-
"""Aula8_Analise_Exploratoria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/
"""

#Importando as bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

#upload do arquivo
from google.colab import files
arq = files.upload()

#Criando nosso dataframe
df = pd.read_excel("AdventureWorks.xlsx")

#Visualizando 5 primeiras linhas
df.head()

#Quantidade de linhas e colunas
df.shape

#Verificando os tipos de dados
df.dtypes

#Qual a receita total?
df["Valor Venda"].sum()

#Qual o custo total?
#Criando a coluna de custo
df["Custo"] = df["Custo Unitário"].mul(df["Quantidade"])

df.head(1)

#Custo total
round(df["Custo"].sum(),2)

#Qual o lucro total? (receita - custo)
df["Lucro"] = df["Valor Venda"] - df["Custo"]

df.head(1)

#Lucro total
round(df["Lucro"].sum(),2)

#Qual o total de dias para entrega do produto?
#Criando coluna
df["Tempo Envio"] = df["Data Envio"] - df["Data Venda"]

df.head(1)

#Qual a média do tempo de envio para cada marca?
df["Tempo Envio"] = (df["Data Envio"] - df["Data Venda"]).dt.days

df.head(1)

df["Tempo Envio"].dtype

#Média de tempo de envio por marca
df.groupby("Marca")["Tempo Envio"].mean()

"""### Missing values"""

df.isnull().sum()

"""### Voltando para análise"""

#Lucro por ano e por marca
df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum()

#Corrigindo a notação científica
pd.options.display.float_format = '{:20,.2f}'.format

#Resetando o index
lucro_ano = df.groupby([df["Data Venda"].dt.year, "Marca"])["Lucro"].sum().reset_index()

lucro_ano

#Qual o total de produtos vendidos?
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=False)

#Grafico total de produtos vendidos
df.groupby("Produto")["Quantidade"].sum().sort_values(ascending=True).plot.barh(title="Total de Produtos Vendidos")
plt.xlabel("Total")
plt.ylabel("Produto");

df.groupby(df["Data Venda"].dt.year)["Lucro"].sum().plot.bar(title="Lucro/Ano")
plt.xlabel("Ano")
plt.ylabel("Receita");

#Selecionando apenas vendas de 2009
df_2009 = df[df["Data Venda"].dt.year == 2009]

df_2009.head(5)

df_2009.shape

from matplotlib import markers
df_2009.groupby(df_2009["Data Venda"].dt.month)["Lucro"].sum().plot(title="Lucro/mês",marker="o")
plt.xlabel("Mês")
plt.ylabel("Lucro Total")
plt.legend;

#Grafico de barras
df_2009.groupby("Marca")["Lucro"].sum().plot.bar(title="Lucro/Marca")
plt.xlabel("Marca")
plt.xticks(rotation='horizontal')
plt.ylabel("Lucro total");

#Grafico Lucro por classe
df_2009.groupby("Classe")["Lucro"].sum().plot.bar(title="Lucro/Classe")
plt.xlabel("Classe")
plt.xticks(rotation='horizontal')
plt.ylabel("Lucro total");

df["Tempo Envio"].describe()

#Grafico de boxplot
plt.boxplot(df["Tempo Envio"]);

plt.hist(df["Tempo Envio"]);

#Tempo mínimo de envio
df["Tempo Envio"].min()

#Tempo máximo de envio
df["Tempo Envio"].max()

df[df["Tempo Envio"] == 20]

df.to_csv("df_vendas_novo.csv",index=False)

